# Generated by Django 4.0.6 on 2023-02-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileForPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True, verbose_name='Filename')),
                ('upload_time', models.DateTimeField(verbose_name='Date-Time')),
                ('code_for_print', models.IntegerField(unique=True, verbose_name='Code for print')),
                ('print_state', models.BooleanField(default=False, verbose_name='Is printed')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.DeleteModel(
            name='FiledForPrint',
        ),
    ]
