# Generated by Django 4.0.6 on 2023-02-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printform', '0003_fileforprint_amount_fileforprint_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileforprint',
            name='payment',
        ),
    ]
