# Generated by Django 4.0.6 on 2023-03-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printform', '0004_remove_fileforprint_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileforprint',
            options={},
        ),
    ]
